version: "3.8"

services:
  # LocalStack
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts:/etc/localstack/init/ready.d"
      - "./data:/home/localstack/data"

  # LocalStack 操作用の Linux クライアント
  localstack_client:
    build: ./_ubuntu
    container_name: localstack_client
    hostname: localstack_client
    restart: always
    volumes:
      #  - ./volume/home:/home
      - ./sls/:/opt/slstest/example1
    tty: true
    #command: >
    #  sh -c "bash"
    environment:
      TZ: Asia/Tokyo
      ENDPOINT_URL: http://localstack:4566
