version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8081:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - ./files:/usr/src/redmine/files
      - ./redmine_plagins:/usr/src/redmine/plugins
      - ./git:/var/git

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
     - ./musql/db:/var/lib/sql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci