global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets:
          - "host.docker.internal:9100"
  - job_name: "node2"
    static_configs:
      - targets:
          - "node-exporter:9100"
# remote_write:
#   - url: "http://influxdb:8086/api/v1/prom/write?db=bucket"

# remote_read:
#   - url: "http://influxdb:8086/api/v1/prom/read?db=bucket"
